# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kmeans.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ckmeans.proto\"\x1d\n\rKMeansRequest\x12\x0c\n\x04temp\x18\x01 \x01(\x08\"!\n\x0eKMeansResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"e\n\nMapRequest\x12\x11\n\tmapper_id\x18\x01 \x01(\x05\x12\x13\n\x0bstart_index\x18\x02 \x01(\x05\x12\x11\n\tend_index\x18\x03 \x01(\x05\x12\x1c\n\tcentroids\x18\x04 \x03(\x0b\x32\t.Centroid\"\x1e\n\x0bMapResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"$\n\rReduceRequest\x12\x13\n\x0b\x63\x65ntroid_id\x18\x01 \x01(\x05\"P\n\x0eReduceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x13\n\x0b\x63\x65ntroid_id\x18\x02 \x01(\x05\x12\x18\n\x10updated_centroid\x18\x03 \x03(\x01\"!\n\tDataPoint\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\".\n\x08\x43\x65ntroid\x12\x13\n\x0b\x63\x65ntroid_id\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x03(\x01\x32\x89\x01\n\x06KMeans\x12.\n\tRunKMeans\x12\x0e.KMeansRequest\x1a\x0f.KMeansResponse\"\x00\x12\"\n\x03Map\x12\x0b.MapRequest\x1a\x0c.MapResponse\"\x00\x12+\n\x06Reduce\x12\x0e.ReduceRequest\x1a\x0f.ReduceResponse\"\x00\x32,\n\x06Mapper\x12\"\n\x03Map\x12\x0b.MapRequest\x1a\x0c.MapResponse\"\x00\x32\x36\n\x07Reducer\x12+\n\x06Reduce\x12\x0e.ReduceRequest\x1a\x0f.ReduceResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kmeans_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_KMEANSREQUEST']._serialized_start=16
  _globals['_KMEANSREQUEST']._serialized_end=45
  _globals['_KMEANSRESPONSE']._serialized_start=47
  _globals['_KMEANSRESPONSE']._serialized_end=80
  _globals['_MAPREQUEST']._serialized_start=82
  _globals['_MAPREQUEST']._serialized_end=183
  _globals['_MAPRESPONSE']._serialized_start=185
  _globals['_MAPRESPONSE']._serialized_end=215
  _globals['_REDUCEREQUEST']._serialized_start=217
  _globals['_REDUCEREQUEST']._serialized_end=253
  _globals['_REDUCERESPONSE']._serialized_start=255
  _globals['_REDUCERESPONSE']._serialized_end=335
  _globals['_DATAPOINT']._serialized_start=337
  _globals['_DATAPOINT']._serialized_end=370
  _globals['_CENTROID']._serialized_start=372
  _globals['_CENTROID']._serialized_end=418
  _globals['_KMEANS']._serialized_start=421
  _globals['_KMEANS']._serialized_end=558
  _globals['_MAPPER']._serialized_start=560
  _globals['_MAPPER']._serialized_end=604
  _globals['_REDUCER']._serialized_start=606
  _globals['_REDUCER']._serialized_end=660
# @@protoc_insertion_point(module_scope)
