# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kmeans_pb2 as kmeans__pb2


class KMeansStub(object):
    """Define KMeans service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunKMeans = channel.unary_unary(
                '/KMeans/RunKMeans',
                request_serializer=kmeans__pb2.KMeansRequest.SerializeToString,
                response_deserializer=kmeans__pb2.KMeansResponse.FromString,
                )
        self.Map = channel.unary_unary(
                '/KMeans/Map',
                request_serializer=kmeans__pb2.MapRequest.SerializeToString,
                response_deserializer=kmeans__pb2.MapResponse.FromString,
                )
        self.Reduce = channel.unary_unary(
                '/KMeans/Reduce',
                request_serializer=kmeans__pb2.ReduceRequest.SerializeToString,
                response_deserializer=kmeans__pb2.ReduceResponse.FromString,
                )


class KMeansServicer(object):
    """Define KMeans service
    """

    def RunKMeans(self, request, context):
        """RPC method for master to run KMeans algorithm
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Map(self, request, context):
        """RPC method for mapper to process data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reduce(self, request, context):
        """RPC method for reducer to update centroid
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KMeansServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunKMeans': grpc.unary_unary_rpc_method_handler(
                    servicer.RunKMeans,
                    request_deserializer=kmeans__pb2.KMeansRequest.FromString,
                    response_serializer=kmeans__pb2.KMeansResponse.SerializeToString,
            ),
            'Map': grpc.unary_unary_rpc_method_handler(
                    servicer.Map,
                    request_deserializer=kmeans__pb2.MapRequest.FromString,
                    response_serializer=kmeans__pb2.MapResponse.SerializeToString,
            ),
            'Reduce': grpc.unary_unary_rpc_method_handler(
                    servicer.Reduce,
                    request_deserializer=kmeans__pb2.ReduceRequest.FromString,
                    response_serializer=kmeans__pb2.ReduceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'KMeans', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KMeans(object):
    """Define KMeans service
    """

    @staticmethod
    def RunKMeans(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KMeans/RunKMeans',
            kmeans__pb2.KMeansRequest.SerializeToString,
            kmeans__pb2.KMeansResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Map(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KMeans/Map',
            kmeans__pb2.MapRequest.SerializeToString,
            kmeans__pb2.MapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Reduce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KMeans/Reduce',
            kmeans__pb2.ReduceRequest.SerializeToString,
            kmeans__pb2.ReduceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class MapperStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Map = channel.unary_unary(
                '/Mapper/Map',
                request_serializer=kmeans__pb2.MapRequest.SerializeToString,
                response_deserializer=kmeans__pb2.MapResponse.FromString,
                )


class MapperServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Map(self, request, context):
        """RPC method for mapping data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MapperServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Map': grpc.unary_unary_rpc_method_handler(
                    servicer.Map,
                    request_deserializer=kmeans__pb2.MapRequest.FromString,
                    response_serializer=kmeans__pb2.MapResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Mapper', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Mapper(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Map(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Mapper/Map',
            kmeans__pb2.MapRequest.SerializeToString,
            kmeans__pb2.MapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ReducerStub(object):
    """Define Reducer service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Reduce = channel.unary_unary(
                '/Reducer/Reduce',
                request_serializer=kmeans__pb2.ReduceRequest.SerializeToString,
                response_deserializer=kmeans__pb2.ReduceResponse.FromString,
                )


class ReducerServicer(object):
    """Define Reducer service
    """

    def Reduce(self, request, context):
        """RPC method for reducing data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReducerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Reduce': grpc.unary_unary_rpc_method_handler(
                    servicer.Reduce,
                    request_deserializer=kmeans__pb2.ReduceRequest.FromString,
                    response_serializer=kmeans__pb2.ReduceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Reducer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Reducer(object):
    """Define Reducer service
    """

    @staticmethod
    def Reduce(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Reducer/Reduce',
            kmeans__pb2.ReduceRequest.SerializeToString,
            kmeans__pb2.ReduceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
